name: Generate Combinations

on:
  workflow_dispatch:

jobs:
  generate-combinations:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Define fruits and names
        id: define_lists
        run: |
          $env:FRUITS = "pomme,banane,orange,fraise"
          $env:NAMES = "Michel,Paul,Claire"

      - name: Generate and display combinations
        run: |
          $fruits = $env:FRUITS -split ","
          $names = $env:NAMES -split ","

          foreach ($name in $names) {
            foreach ($fruit in $fruits) {
              Write-Output "$name mange une $fruit, et il adore ça !"
            }
          }
