# .github/workflows/next-one.yml
name: Next One

on:
  workflow_run:
    workflows: ["Pull Request Closed"]
    types:
      - completed

jobs:
  next-message:
    runs-on: windows-latest
    steps:
      - name: Print next one message
        run: echo 'Workflow précédent terminé, maintenant c\'est au tour de celui-ci'
